---
- name: "Update System (Debian)"
  apt: update_cache=yes cache_valid_time=86400 upgrade=dist
  when: "'{{ ansible_os_family }}' == 'Debian'"

- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades state=present

- name: Remove memory limit constraints from cron job
  lineinfile: >
    dest=/etc/cron.daily/apt
    insertafter="^# -+ main -+"
    line="ulimit -s unlimited"
    state=present

- name: Remove memory limit constraints from cron job
  lineinfile: >
    dest=/etc/environment
    line="{{ item }}"
    state=present
  with_items:
    - "LANG=en_US.UTF-8"
    - "LC_ALL=en_US.UTF-8"

- name: "Check if reboot is required"
  stat: path=/var/run/reboot-required
  register: reboot_required

- name: "Reboot server"
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: reboot_required.stat.exists

- name: waiting for server to come back
  local_action: wait_for host={{ ansible_host }} port={{ ansible_port | default(22) }} state=started
  become: false
