---
- name: "Install Development Tools"
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - tree
    - vim
    - php-xdebug

- name: "Check NPM intialized"
  stat: path={{ root }}/node_modules
  become: yes
  become_user: "{{ web_user }}"
  register: installed

- name: "Install NPM packages"
  command: chdir={{ root }} npm install
  become: yes
  become_user: "{{ web_user }}"
  when: installed.stat.exists == False
