---
- name: "Install Tools"
  apt: pkg={{ item }} state=present
  with_items:
    - vim
    - landscape-common
    - acl

- name: "Configure timezone file"
  copy: content="{{ timezone }}" dest=/etc/timezone

- name: "Reconfigure timezone"
  command: dpkg-reconfigure -f noninteractive tzdata

- name: "Set VIM as default editor"
  command: update-alternatives --set editor /usr/bin/vim.basic

- name: "Set hostname"
  template: >
    src=hostname.j2
    dest=/etc/hostname

- name: "Add hosts"
  lineinfile: >
    dest=/etc/hosts
    regexp='.* {{ item }}$'
    line="127.0.1.1 {{item}}"
    state=present
  with_items:
    - "{{ host }}"
    - "mail.{{ host }}"
